// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD_Vcd5M6QbyFAtWyW0fUChYV0D3NecZk',
    appId: '1:981810997654:web:1e75692718f5c6ce4ed5b7',
    messagingSenderId: '981810997654',
    projectId: 'emotion-detection-53a5c',
    authDomain: 'emotion-detection-53a5c.firebaseapp.com',
    storageBucket: 'emotion-detection-53a5c.appspot.com',
    measurementId: 'G-41JHFLXY07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnkiHaK7hVyDSRQEodHvpQuTVzv0656GI',
    appId: '1:981810997654:android:da8ddb6d3f628a374ed5b7',
    messagingSenderId: '981810997654',
    projectId: 'emotion-detection-53a5c',
    storageBucket: 'emotion-detection-53a5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkbFiLS9WNCgi2Jyg4Uh8d-Gv98YyuMFo',
    appId: '1:981810997654:ios:f76d8894917ff8004ed5b7',
    messagingSenderId: '981810997654',
    projectId: 'emotion-detection-53a5c',
    storageBucket: 'emotion-detection-53a5c.appspot.com',
    iosBundleId: 'com.example.emotionDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkbFiLS9WNCgi2Jyg4Uh8d-Gv98YyuMFo',
    appId: '1:981810997654:ios:f0f2f230fb10a9434ed5b7',
    messagingSenderId: '981810997654',
    projectId: 'emotion-detection-53a5c',
    storageBucket: 'emotion-detection-53a5c.appspot.com',
    iosBundleId: 'com.example.emotionDetection.RunnerTests',
  );
}
